// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_read_flare
DataFrame rcpp_read_flare(std::string flare_file);
RcppExport SEXP _HAUDI_rcpp_read_flare(SEXP flare_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type flare_file(flare_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_read_flare(flare_file));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_query_tracts
List rcpp_query_tracts(const IntegerVector& left_haps, const IntegerVector& right_haps, const IntegerVector& breakpoints, const IntegerVector& offsets, const IntegerVector& indices);
RcppExport SEXP _HAUDI_rcpp_query_tracts(SEXP left_hapsSEXP, SEXP right_hapsSEXP, SEXP breakpointsSEXP, SEXP offsetsSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type left_haps(left_hapsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type right_haps(right_hapsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type breakpoints(breakpointsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_query_tracts(left_haps, right_haps, breakpoints, offsets, indices));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_read_rfmix
DataFrame rcpp_read_rfmix(std::string msp_file);
RcppExport SEXP _HAUDI_rcpp_read_rfmix(SEXP msp_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type msp_file(msp_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_read_rfmix(msp_file));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HAUDI_rcpp_read_flare", (DL_FUNC) &_HAUDI_rcpp_read_flare, 1},
    {"_HAUDI_rcpp_query_tracts", (DL_FUNC) &_HAUDI_rcpp_query_tracts, 5},
    {"_HAUDI_rcpp_read_rfmix", (DL_FUNC) &_HAUDI_rcpp_read_rfmix, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_HAUDI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
