# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_read_flare <- function(flare_file) {
    .Call(`_HAUDI_rcpp_read_flare`, flare_file)
}

rcpp_query_tracts <- function(left_haps, right_haps, breakpoints, offsets, indices) {
    .Call(`_HAUDI_rcpp_query_tracts`, left_haps, right_haps, breakpoints, offsets, indices)
}

rcpp_get_masked_geno <- function(anc0, anc1, gen0, gen1, n_anc) {
    .Call(`_HAUDI_rcpp_get_masked_geno`, anc0, anc1, gen0, gen1, n_anc)
}

rcpp_read_rfmix <- function(msp_file) {
    .Call(`_HAUDI_rcpp_read_rfmix`, msp_file)
}

