# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_read_flare <- function(flare_file) {
    .Call('_HAUDI_rcpp_read_flare', PACKAGE = 'HAUDI', flare_file)
}

rcpp_read_rfmix <- function(msp_file) {
    .Call('_HAUDI_rcpp_read_rfmix', PACKAGE = 'HAUDI', msp_file)
}

