# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_read_flare <- function(flare_file) {
    .Call(`_HAUDI_rcpp_read_flare`, flare_file)
}

rcpp_parse_lanc <- function(lines) {
    .Call(`_HAUDI_rcpp_parse_lanc`, lines)
}

rcpp_query_tracts <- function(query_indices, tract_data) {
    .Call(`_HAUDI_rcpp_query_tracts`, query_indices, tract_data)
}

rcpp_read_rfmix <- function(msp_file) {
    .Call(`_HAUDI_rcpp_read_rfmix`, msp_file)
}

